import React, { createContext, useState, useContext } from 'react';
import type { ReactNode } from 'react';

type Language = 'en' | 'hi' | 'ta' | 'ne';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    welcome: "Welcome Back",
    selectProfile: "Select your profile to sign in",
    quickLogin: "Quick Face Login",
    scanning: "Scanning Face...",
    verifying: "Verifying Identity",
    verifyingLabel: "VERIFYING",
    lookAtCamera: "Please look directly at the camera",
    accessDenied: "Access Denied",
    placeFace: "Place your face in front of the camera to continue",
    footer: "Secured by Biometric Trust™",
    dashboard: "Field Monitoring",
    realtime: "Real-time soil moisture & aerial surveillance",
    allSectors: "All Sectors",
    criticalOnly: "Critical Only",
    voiceCommand: "VOICE COMMAND",
    listening: "LISTENING",
    assistantStandby: "ASSISTANT: STANDBY",
    northRidge: "North Ridge Plains",
    eastBasin: "East Basin Wetland",
    highland: "Highland Plateau",
    southValley: "South Valley Dryland",
    riverBend: "River Bend Terrace",
    lowerOrchard: "Lower Orchard",
    needsWater: "NEEDS WATER",
    optimal: "OPTIMAL",
    attention: "ATTENTION REQUIRED",
    backToFields: "Back to Fields",
    help: "Help",
    soilAnalysis: "Soil Analysis",
    today: "TODAY",
    phLevels: "PH Levels",
    moisture: "Moisture",
    optimalRange: "Optimal Range",
    status: "Status",
    stable: "Stable",
    npkLevels: "NPK Levels",
    soilInsight: "Soil Insight",
    soilInsightText: "Excellent nitrogen levels detected. Soil is prime for nitrogen-heavy crops this season.",
    agronomist: "Agronomist",
    irrigationSchedule: "Irrigation Schedule",
    upcoming: "Upcoming",
    gallons: "Gallons",
    completed: "Completed",
    waterUsage: "Water Usage",
    liters: "Liters",
    efficiency: "Efficiency",
    weeklyStats: "Weekly Stats",
    recommendation: "Recommendation",
    recommendationText: "Based on current soil moisture levels and upcoming weather forecast, it is recommended to irrigate Sector A-1 tomorrow morning.",
    refreshSensors: "Refresh Sensors",
    topRecommendations: "Top Recommendations",
    recommendationsSubtitle: "Based on current soil conditions and market trends",
    winterWheat: "Winter Wheat",
    optimalChoice: "OPTIMAL CHOICE",
    highYield: "High Yield",
    days90_120: "90-120 Days",
    days105_150: "105-150 Days",
    rice: "Oryza Sativa (Rice)",
    highlyCompatible: "HIGHLY COMPATIBLE",
    wetland: "Wetland",
    sweetCorn: "Sweet Corn",
    alternative: "ALTERNATIVE",
    cornDescription: "Excellent for current soil moisture. Market demand is rising for sweet corn in the local region.",
    organic: "Organic",
    compatible: "Compatible",
    marketPrice: "Market Price",
    agriAssistant: "Agri Assistant",
    voiceActive: "Voice Active",
    voicePrompt: "\"What should I plant in Section 4?\"",
    listen: "LISTEN",
    recentCommands: "RECENT COMMANDS",
    command1: "\"Analyze soil moisture trends...\"",
    command2: "\"Compare wheat and corn yields...\"",
  },
  hi: {
    welcome: "वापसी पर स्वागत है",
    selectProfile: "साइन इन करने के लिए अपनी प्रोफ़ाइल चुनें",
    quickLogin: "त्वरित चेहरा लॉगिन",
    scanning: "चेहरा स्कैन किया जा रहा है...",
    verifying: "पहचान सत्यापित की जा रही है",
    verifyingLabel: "सत्यापन",
    lookAtCamera: "कृपया सीधे कैमरे की ओर देखें",
    accessDenied: "प्रवेश अस्वीकृत",
    placeFace: "जारी रखने के लिए अपना चेहरा कैमरे के सामने रखें",
    footer: "बायोमेट्रिक ट्रस्ट™ द्वारा सुरक्षित",
    dashboard: "खेत की निगरानी",
    realtime: "वास्तविक समय मिट्टी की नमी और हवाई निगरानी",
    allSectors: "सभी क्षेत्र",
    criticalOnly: "केवल महत्वपूर्ण",
    voiceCommand: "वॉइस कमांड",
    listening: "सुन रहा हूँ",
    assistantStandby: "सहायक: स्टैंडबाय",
    northRidge: "उत्तर रिज मैदान",
    eastBasin: "पूर्व बेसिन वेटलैंड",
    highland: "हाइलैंड पठार",
    southValley: "दक्षिण घाटी सूखी भूमि",
    riverBend: "नदी मोड़ छत",
    lowerOrchard: "निचला बाग",
    needsWater: "पानी की आवश्यकता है",
    optimal: "इष्टतम",
    attention: "ध्यान आवश्यक है",
    backToFields: "खेतों पर वापस जाएँ",
    help: "मदद",
    soilAnalysis: "मिट्टी विश्लेषण",
    today: "आज",
    phLevels: "पीएच स्तर",
    moisture: "नमी",
    optimalRange: "इष्टतम रेंज",
    status: "स्थिति",
    stable: "स्थिर",
    npkLevels: "एनपीके स्तर",
    soilInsight: "मिट्टी की जानकारी",
    soilInsightText: "उत्कृष्ट नाइट्रोजन स्तर का पता चला। यह मौसम नाइट्रोजन-भारी फसलों के लिए सर्वोत्तम है।",
    agronomist: "कृषि विज्ञानी",
    irrigationSchedule: "सिंचाई अनुसूची",
    upcoming: "आगामी",
    gallons: "गैलन",
    completed: "पूर्ण",
    waterUsage: "जल उपयोग",
    liters: "लीटर",
    efficiency: "दक्षता",
    weeklyStats: "साप्ताहिक आँकड़े",
    recommendation: "सिफारिश",
    recommendationText: "वर्तमान मिट्टी की नमी के स्तर और आगामी मौसम के पूर्वानुमान के आधार पर, कल सुबह सेक्टर ए-1 की सिंचाई करने की सिफारिश की जाती है।",
    refreshSensors: "सेंसर रिफ्रेश करें",
    topRecommendations: "शीर्ष सिफारिशें",
    recommendationsSubtitle: "वर्तमान मिट्टी की स्थिति और बाजार के रुझान के आधार पर",
    winterWheat: "शीतकालीन गेहूं",
    optimalChoice: "इष्टतम विकल्प",
    highYield: "उच्च उपज",
    days90_120: "९०-१२० दिन",
    days105_150: "१०५-१५० दिन",
    rice: "धान (चावल)",
    highlyCompatible: "अत्यधिक संगत",
    wetland: "आर्द्रभूमि",
    sweetCorn: "स्वीट कॉर्न",
    alternative: "वैकल्पिक",
    cornDescription: "वर्तमान मिट्टी की नमी के लिए उत्कृष्ट। स्थानीय क्षेत्र में स्वीट कॉर्न की बाजार मांग बढ़ रही है।",
    organic: "जैविक",
    compatible: "संगत",
    marketPrice: "बाजार मूल्य",
    agriAssistant: "कृषि सहायक",
    voiceActive: "वॉयस सक्रिय",
    voicePrompt: "मुझे सेक्टर 4 में क्या लगाना चाहिए?",
    listen: "सुनें",
    recentCommands: "हाल के कमांड",
    command1: "मिट्टी की नमी के रुझान का विश्लेषण करें...",
    command2: "गेहूं और मक्का की पैदावार की तुलना करें..."
  },
  ta: {
    welcome: "மீண்டும் வருக",
    selectProfile: "உள்நுழைய உங்கள் சுயவிவரத்தைத் தேர்ந்தெடுக்கவும்",
    quickLogin: "விரைவு முக உள்நுழைவு",
    scanning: "முகம் ஸ்கேன் செய்யப்படுகிறது...",
    verifying: "அடையாளத்தை சரிபார்க்கிறது",
    verifyingLabel: "சரிபார்த்தல்",
    lookAtCamera: "தயவுசெய்து கேமராவை நேரடியாகப் பார்க்கவும்",
    accessDenied: "அணுகல் மறுக்கப்பட்டது",
    placeFace: "தொடர உங்கள் முகத்தை கேமராவின் முன் வைக்கவும்",
    footer: "பயோமெட்ரிக் ட்ரஸ்ட்™ மூலம் பாதுகாக்கப்பட்டது",
    dashboard: "வயல் கண்காணிப்பு",
    realtime: "நிகழ்நேர மண் ஈரப்பதம் மற்றும் வான்வழி கண்காணிப்பு",
    allSectors: "அனைத்து துறைகளும்",
    criticalOnly: "முக்கியமானது மட்டும்",
    voiceCommand: "குரல் கட்டளை",
    listening: "கேட்கிறது",
    assistantStandby: "உதவியாளர்: காத்திருப்பு",
    northRidge: "வடக்கு ரிட்ஜ் சமவெளி",
    eastBasin: "கிழக்கு படுகை ஈரம்",
    highland: "உயர்நில பீடபூமி",
    southValley: "தெற்கு பள்ளத்தாக்கு வறண்ட நிலம்",
    riverBend: "ஆற்று வளைவு மொட்டை மாடி",
    lowerOrchard: "கீழ் பழத்தோட்டம்",
    needsWater: "தண்ணீர் தேவை",
    optimal: "சிறந்தது",
    attention: "கவனம் தேவை",
    backToFields: "வயல்களுக்குத் திரும்பு",
    help: "உதவி",
    soilAnalysis: "மண் ஆய்வு",
    today: "இன்று",
    phLevels: "பி.எச் அளவுகள்",
    moisture: "ஈரப்பதம்",
    optimalRange: "சிறந்த வரம்பு",
    status: "நிலை",
    stable: "நிலையான",
    npkLevels: "NPK அளவுகள்",
    soilInsight: "மண் நுண்ணறிவு",
    soilInsightText: "சிறந்த நைட்ரஜன் நிலைகள் கண்டறியப்பட்டன. இந்த பருவத்தில் நைட்ரஜன் நிறைந்த பயிர்களுக்கு மண் சிறந்தது.",
    agronomist: "வேளாண் நிபுணர்",
    irrigationSchedule: "நீர்ப்பாசன அட்டவணை",
    upcoming: "உடனடி",
    gallons: "காலன்கள்",
    completed: "முடிந்தது",
    waterUsage: "நீர் பயன்பாடு",
    liters: "லிட்டர்",
    efficiency: "திறன்",
    weeklyStats: "வாராந்திர புள்ளிவிவரங்கள்",
    recommendation: "பரிந்துரை",
    recommendationText: "தற்போதைய மண் ஈரப்பத நிலைகள் மற்றும் வரவிருக்கும் வானிலை முன்னறிவிப்பின் அடிப்படையில், நாளைக் காலை துறை A-1 க்கு நீர்ப்பாசனம் செய்ய பரிந்துரைக்கப்படுகிறது.",
    refreshSensors: "சென்சார்களைப் புதுப்பிக்கவும்",
    topRecommendations: "சிறந்த பரிந்துரைகள்",
    recommendationsSubtitle: "தற்போதைய மண் நிலைகள் மற்றும் சந்தை போக்குகளின் அடிப்படையில்",
    winterWheat: "குளிர்கால கோதுமை",
    optimalChoice: "சிறந்த தேர்வு",
    highYield: "அதிக விளைச்சல்",
    days90_120: "90-120 நாட்கள்",
    days105_150: "105-150 நாட்கள்",
    rice: "நெல்",
    highlyCompatible: "மிகவும் பொருந்தக்கூடியது",
    wetland: "ஈரநிலம்",
    sweetCorn: "இனிப்பு மக்காச்சோளம்",
    alternative: "மாற்று",
    cornDescription: "தற்போதைய மண் ஈரப்பதத்திற்கு சிறந்தது. உள்ளூர் பிராந்தியத்தில் இனிப்பு மக்காச்சோளத்திற்கு சந்தை தேவை அதிகரிக்கிறது.",
    organic: "இயற்கை",
    compatible: "பொருந்தக்கூடியது",
    marketPrice: "சந்தை விலை",
    agriAssistant: "விவசாய உதவியாளர்",
    voiceActive: "குரல் செயலில்",
    voicePrompt: "பிரிவு 4 இல் நான் என்ன பயிரிட வேண்டும்?",
    listen: "கேள்",
    recentCommands: "சமீபத்திய கட்டளைகள்",
    command1: "மண் ஈரப்பதப் போக்குகளைப் பகுப்பாய்வு செய்க...",
    command2: "கோதுமை மற்றும் சோள விளைச்சல்களை ஒப்பிடுக..."
  },
  ne: {
    welcome: "फिर्ता स्वागत छ",
    selectProfile: "साइन इन गर्न आफ्नो प्रोफाइल चयन गर्नुहोस्",
    quickLogin: "द्रुत अनुहार लगइन",
    scanning: "अनुहार स्क्यान गर्दै...",
    verifying: "पहिचान प्रमाणित गर्दै",
    verifyingLabel: "प्रमाणीकरण",
    lookAtCamera: "कृपया सीधा क्यामेरामा हेर्नुहोस्",
    accessDenied: "प्रवेश अस्वीकृत",
    placeFace: "जारी राख्न आफ्नो अनुहार क्यामेराको अगाडि राख्नुहोस्",
    footer: "बायोमेट्रिक ट्रस्ट™ द्वारा सुरक्षित",
    dashboard: "क्षेत्र निगरानी",
    realtime: "वास्तविक समय माटो नमी र हवाई निगरानी",
    allSectors: "सबै क्षेत्रहरू",
    criticalOnly: "केवल महत्वपूर्ण",
    voiceCommand: "आवाज आदेश",
    listening: "सुन्दै",
    assistantStandby: "सहायक: स्ट्यान्डबाइ",
    northRidge: "उत्तर रिज मैदानहरू",
    eastBasin: "पूर्व बेसिन वेटल्याण्ड",
    highland: "हाइल्याण्ड पठार",
    southValley: "दक्षिण उपत्यका सुख्खा भूमि",
    riverBend: "नदी बेन्ड टेरेस",
    lowerOrchard: "तल्लो बगैंचा",
    needsWater: "पानी चाहिन्छ",
    optimal: "इष्टतम",
    attention: "ध्यान आवश्यक",
    backToFields: "खेतहरूमा फर्कनुहोस्",
    help: "मद्दत",
    soilAnalysis: "माटो विश्लेषण",
    today: "आज",
    phLevels: "PH स्तरहरू",
    moisture: "नमी",
    optimalRange: "इष्टतम दायरा",
    status: "स्थिति",
    stable: "स्थिर",
    npkLevels: "NPK स्तरहरू",
    soilInsight: "माटोको जानकारी",
    soilInsightText: "उत्कृष्ट नाइट्रोजन स्तर पत्ता लाग्यो। यो मौसम नाइट्रोजन-भारी बालीहरूका लागि उत्तम छ।",
    agronomist: "कृषि वैज्ञानिक",
    irrigationSchedule: "सिंचाई तालिका",
    upcoming: "आगामी",
    gallons: "ग्यालन",
    completed: "पूरा भयो",
    waterUsage: "पानी प्रयोग",
    liters: "लिटर",
    efficiency: "दक्षता",
    weeklyStats: "साप्ताहिक तथ्याङ्क",
    recommendation: "सिफारिस",
    recommendationText: "हालको माटोको नमीको स्तर र आगामी मौसम पूर्वानुमानका आधारमा, भोलि बिहान सेक्टर A-1 मा सिंचाइ गर्न सिफारिस गरिन्छ।",
    refreshSensors: "सेन्सर रिफ्रेस गर्नुहोस्",
    topRecommendations: "शीर्ष सिफारिसहरू",
    recommendationsSubtitle: "हालको माटोको अवस्था र बजार प्रचलनमा आधारित",
    winterWheat: "हिउँदे गहुँ",
    optimalChoice: "उत्कृष्ट विकल्प",
    highYield: "उच्च उत्पादन",
    days90_120: "90-120 दिन",
    days105_150: "105-150 दिन",
    rice: "धान (चामल)",
    highlyCompatible: "अत्यधिक उपयुक्त",
    wetland: "सिमसार",
    sweetCorn: "मिठो मकै",
    alternative: "वैकल्पिक",
    cornDescription: "हालको माटोको चिस्यानको लागि उत्कृष्ट। स्थानीय क्षेत्रमा मिठो मकैको बजार माग बढ्दो छ।",
    organic: "अर्गानिक",
    compatible: "उपयुक्त",
    marketPrice: "बजार मूल्य",
    agriAssistant: "कृषि सहायक",
    voiceActive: "आवाज सक्रिय",
    voicePrompt: "\"खण्ड ४ मा मैले के रोप्नु पर्छ?\"",
    listen: "सुन्नुहोस्",
    recentCommands: "भर्खरका आदेशहरू",
    command1: "\"माटोको चिस्यानको प्रवृत्तिको विश्लेषण गर्नुहोस्...\"",
    command2: "\"गहुँ र मकैको उत्पादन तुलना गर्नुहोस्...\""
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
